Repository knative-sandbox/control-protocol, pull requests merged in 2021-05, with the labels that each got.

#67 `Connection` interface doesn't use channels anymore
  pkg/connection.go
  pkg/network/base_connection.go
  pkg/service/service.go
  pkg/service/service_caching_wrapper_test.go
  pkg/service/service_test.go
  pkg/test/connection_mock.go
Labels: approved, cla: yes, lgtm, size/L

#68 Removed internal channels and replaced with a proper queue
  pkg/connection.go
  pkg/network/base_connection.go
  pkg/network/base_connection_test.go
  pkg/network/client_connection.go
  pkg/network/client_connection_test.go
  pkg/network/errors.go
  pkg/network/message_queue.go
  pkg/network/server_connection.go
  pkg/network/server_connection_test.go
  pkg/service/service.go
  pkg/test/connection_mock.go
Labels: approved, cla: yes, lgtm, size/XL

#69 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#64 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#71 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#72 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#74 Remove CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#75 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#77 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S
