Repository knative-sandbox/control-protocol, pull requests merged in 2021-12, with the labels that each got.

#130 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/kmap/lookup.go
  vendor/knative.dev/pkg/kmap/map.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/reconciler/filter.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/L

#131 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, size/XS, approved

#132 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, lgtm, size/XS, approved

#133 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, size/XS, approved

#134 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, size/XS, approved

#137 Aligning the dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/S, lgtm, approved
