Repository knative-sandbox/control-protocol, pull requests merged in 2021-03, with the labels that each got.

#4 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XL

#5 [Automated] Format markdown
  README.md
Labels: approved, cla: yes, lgtm, size/S

#7 Fix CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#17 [main] Upgrade to latest dependencies
  go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
Labels: approved, cla: yes, lgtm, size/M

#18 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#19 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#20 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#16 Use different ports in testing to enable parallel tests
  pkg/network/client_connection.go
  pkg/network/e2e_network_test.go
  pkg/network/server_connection.go
  pkg/reconciler/connection_pool_test.go
  pkg/reconciler/message_router_test.go
Labels: approved, cla: yes, lgtm, size/L

#21 Unit tests for service package
  pkg/message.go
  pkg/service.go
  pkg/service/message_router_test.go
  pkg/service/service_caching_wrapper_test.go
  pkg/service/service_test.go
  pkg/test/connection_mock.go
  pkg/test/payload_marshaller_mock.go
  pkg/test/service_mock.go
Labels: approved, cla: yes, lgtm, size/L

#22 Deduplicated a lot of code
  pkg/network/constants.go
  pkg/network/e2e_network_test.go
  pkg/network/network_test.go
  pkg/reconciler/connection_pool_test.go
  pkg/reconciler/message_router_test.go
  pkg/reconciler/notification_store_test.go
  pkg/service/message_router_test.go
  pkg/service/service_caching_wrapper_test.go
  pkg/service/service_test.go
  pkg/test/connection_mock.go
  pkg/test/payload_marshaller_mock.go
  pkg/test/service_mock.go
  pkg/test/tls.go
  pkg/test/util.go
Labels: approved, cla: yes, lgtm, size/XXL

#26 Trying to fix client connection close race
  pkg/network/base_connection.go
  pkg/network/server_connection.go
Labels: approved, cla: yes, lgtm, size/M

#24 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#28 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/pmezard/go-difflib/difflib/LICENSE
  third_party/VENDOR-LICENSE/github.com/stretchr/testify/LICENSE
  third_party/VENDOR-LICENSE/gopkg.in/yaml.v3/LICENSE
  third_party/VENDOR-LICENSE/gopkg.in/yaml.v3/NOTICE
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#30 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M

#31 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M

#32 [Automated] Update actions
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#33 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/gofuzz/.travis.yml
  vendor/github.com/google/gofuzz/CONTRIBUTING.md
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/bytesource/bytesource.go
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  vendor/google.golang.org/grpc/encoding/proto/proto.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#23 Renamed NotificationStore.ControlMessageHandler to NotificationStore.MessageHandler
  pkg/reconciler/notification_store.go
  pkg/reconciler/notification_store_test.go
Labels: approved, cla: yes, lgtm, size/XS

#27 Really fix that race condition
  pkg/network/base_connection.go
  pkg/network/base_connection_test.go
  pkg/network/client_connection.go
  pkg/network/server_connection.go
  pkg/network/server_connection_test.go
  pkg/service/service.go
Labels: approved, cla: yes, lgtm, size/XL

#34 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#37 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, lgtm, size/XS

#36 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/secret/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M
