Repository knative-sandbox/control-protocol, pull requests merged in 2021-09, with the labels that each got.

#103 drop scheduled actions these fill up the job queue causing delays
  .github/workflows/kind-e2e.yaml
Labels: cla: yes, lgtm, size/XS, approved

#106 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#108 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/M

#107 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/v1/podspec_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/secret/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/secret/state.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/XL

#109 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, size/S, lgtm, approved

#112 [main] Update community files
  CODE-OF-CONDUCT.md
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/L

#111 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, size/S, lgtm, approved
