Repository knative-sandbox/control-protocol, pull requests merged in 2021-04, with the labels that each got.

#38 change arg name
  pkg/network/server_connection.go
Labels: approved, cla: yes, lgtm, size/XS

#39 Increase certificates test
  pkg/certificates/reconciler/certificates_test.go
  pkg/certificates/reconciler/controller.go
Labels: approved, cla: yes, lgtm, size/L

#40 Joined InboundMessage and OutboundMessage under the same struct
  pkg/connection.go
  pkg/message.go
  pkg/network/base_connection.go
  pkg/network/base_connection_test.go
  pkg/network/client_connection.go
  pkg/network/server_connection.go
  pkg/network/server_connection_test.go
  pkg/reconciler/pod_ip_getter_test.go
  pkg/service.go
  pkg/service/message_router_test.go
  pkg/service/service.go
  pkg/service/service_caching_wrapper_test.go
  pkg/service/service_test.go
  pkg/test/connection_mock.go
  pkg/test/service_mock.go
Labels: approved, cla: yes, lgtm, size/L

#41 Enable Codecov
  .codecov.yaml
Labels: approved, cla: yes, lgtm, size/XS

#46 Use max uint8 as ack opcode
  pkg/service.go
Labels: approved, cla: yes, lgtm, size/XS

#48 ServiceMessage.Ack now can propagate an error string back to the sender
  pkg/message.go
  pkg/network/network_test.go
  pkg/service.go
  pkg/service/service.go
  pkg/service/service_test.go
  pkg/test/service_mock.go
Labels: approved, cla: yes, lgtm, size/L

#45 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/secret/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/secret/state.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/network/domain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#49 Utilies to simplify async command use case
  README.md
  docs/README.md
  docs/async_command_pattern.md
  pkg/message/async_command.go
  pkg/message/async_command_result.go
  pkg/message/async_command_result_test.go
  pkg/reconciler/async_command_notification_store.go
  pkg/reconciler/async_command_notification_store_test.go
  pkg/service/async_command_handler.go
  pkg/service/async_command_handler_test.go
  pkg/service/built_in_handlers.go
  pkg/test/service_mock.go
Labels: approved, cla: yes, lgtm, size/XL

#50 Fix port binding race
  pkg/network/network_test.go
  pkg/test/util.go
Labels: approved, cla: yes, lgtm, size/XS

#51 [Automated] Format markdown
  docs/README.md
  docs/async_command_pattern.md
Labels: approved, cla: yes, lgtm, size/S

#59 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#56 Message router now fails when received a message with unknown opcode
  pkg/service/message_router.go
  pkg/service/message_router_test.go
Labels: approved, cla: yes, lgtm, size/XS

#57 Service send with empty payload
  pkg/service/service.go
  pkg/service/service_test.go
Labels: approved, cla: yes, lgtm, size/M

#61 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/secret/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/reconciler-test/pkg/environment/flags.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#62 Copy OWNERS_ALIASES from knative/community; fill in OWNERS files
  OWNERS
  OWNERS_ALIASES
  hack/OWNERS
  test/OWNERS
Labels: approved, cla: yes, lgtm, size/L

#63 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S
