Repository knative-sandbox/control-protocol, pull requests merged in 2021-02, with the labels that each got.

#2 Add wg leads to OWNER_ALIASES
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1 Added readme
  README.md
Labels: approved, cla: yes, lgtm, size/S

#3 Add CODEOWNERS file for approvals
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
