Repository knative-sandbox/control-protocol, pull requests merged in 2021-06, with the labels that each got.

#80 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#81 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#65 TLS conformance test
  pkg/network/tls.go
  test/conformance/conformance_test.go
  test/conformance/feature/conformance_feature.go
  test/conformance/resources/conformance_client/install.go
  test/conformance/resources/conformance_client/job.yaml
  test/conformance/resources/conformance_server/install.go
  test/conformance/resources/conformance_server/pod.yaml
  test/test_images/conformance-go-client/main.go
  test/test_images/conformance-go-server/main.go
Labels: approved, cla: yes, lgtm, size/L

#78 Update deps and go 1.16 bump
  .github/workflows/kind-e2e.yaml
  go.mod
  go.sum
  test/conformance/conformance_test.go
  third_party/VENDOR-LICENSE/LICENSE
  third_party/VENDOR-LICENSE/vendor/golang.org/x/crypto/LICENSE
  third_party/VENDOR-LICENSE/vendor/golang.org/x/net/LICENSE
  third_party/VENDOR-LICENSE/vendor/golang.org/x/sys/cpu/LICENSE
  third_party/VENDOR-LICENSE/vendor/golang.org/x/text/LICENSE
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/knative.dev/reconciler-test/pkg/manifest/templates.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#85 Break out of error polling loop when error channel is closed
  pkg/service/service.go
Labels: approved, cla: yes, kind/bug, lgtm, size/XS

#86 Add interfaces to ConnectionPool and AsyncNotificationStore for testing
  pkg/reconciler/async_command_notification_store.go
  pkg/reconciler/async_command_notification_store_test.go
  pkg/reconciler/connection_pool.go
  pkg/reconciler/connection_pool_option.go
  pkg/test/util.go
Labels: approved, cla: yes, kind/api-change, kind/enhancement, lgtm, size/M

#84 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: approved, cla: yes, lgtm, size/M

#87 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#89 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#88 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS
