Repository knative-sandbox/control-protocol, pull requests merged in 2021-08, with the labels that each got.

#95 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/S, lgtm, approved

#100 Fix Failing Conformance Tests
  .github/workflows/kind-e2e.yaml
  test/conformance/feature/conformance_feature.go
Labels: cla: yes, lgtm, approved, size/M

#101 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/S, lgtm, approved

#102 [main] Update actions
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: cla: yes, lgtm, size/XS, approved
