Repository knative-sandbox/control-protocol, pull requests merged in 2022-10, with the labels that each got.

#217 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#219 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#221 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, size/XS, approved

#220 store certs under different names in secrets
  pkg/certificates/constants.go
  pkg/certificates/reconciler/certificates.go
  pkg/certificates/reconciler/certificates_test.go
Labels: lgtm, approved, size/M, ok-to-test, kind/enhancement

#224 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/knative.dev/reconciler-test/pkg/environment/images.go
  vendor/modules.txt
Labels: lgtm, approved, size/L
