Repository knative-sandbox/control-protocol, pull requests merged in 2022-11, with the labels that each got.

#225 Certificate controller to only watch secrets with a label
  .codecov.yaml
  pkg/certificates/reconciler/certificates_test.go
  pkg/certificates/reconciler/controller.go
  pkg/certificates/reconciler/controller_impl.go
  pkg/certificates/reconciler/reconciler.go
  pkg/doc.go
  pkg/message.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/filtered/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/filtered/secret.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/filtered/fake/fake_filtered_factory.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/filtered/filtered_factory.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL, kind/enhancement

#228 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#231 Use the correct certificate reconciler
  pkg/certificates/reconciler/certificates.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/secret/controller.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/secret/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/secret/state.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL, kind/bug

#230 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/configmap/doc.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/hash/doc.go
  vendor/knative.dev/pkg/injection/doc.go
  vendor/knative.dev/pkg/injection/injection.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/reconciler/testing/hooks.go
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/knative.dev/pkg/reconciler/testing/sorter.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/zipkin/doc.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/manifest/yaml.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#233 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#232 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/test/security/security.go
  vendor/knative.dev/reconciler-test/pkg/k8s/pod.go
  vendor/knative.dev/reconciler-test/pkg/manifest/options.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#234 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  vendor/k8s.io/gengo/examples/set-gen/generators/sets.go
  vendor/k8s.io/gengo/examples/set-gen/sets/byte.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int64.go
  vendor/k8s.io/gengo/examples/set-gen/sets/string.go
  vendor/k8s.io/gengo/generator/import_tracker.go
  vendor/k8s.io/gengo/namer/import_tracker.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/utils/net/port.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#235 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, skip-review
