Repository knative-sandbox/control-protocol, pull requests merged in 2022-08, with the labels that each got.

#203 bump go1.18
  .github/workflows/kind-e2e.yaml
  go.mod
  go.sum
  test/conformance/resources/conformance_client/install.go
  test/conformance/resources/conformance_server/install.go
Labels: lgtm, approved, size/L

#202 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#197 :broom: Accommodate to knative-sandbox/reconciler-test#294
  .github/workflows/kind-e2e.yaml
  .ko.yaml
  test/conformance/conformance_test.go
  test/conformance/feature/conformance_feature.go
  test/conformance/main_test.go
  test/conformance/resources/conformance_client/install.go
  test/conformance/resources/conformance_client/job.yaml
  test/conformance/resources/conformance_server/install.go
  test/conformance/resources/conformance_server/pod.yaml
  vendor/go.opencensus.io/plugin/ochttp/propagation/tracecontext/propagation.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/cleanup.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/crd.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/environment/config.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/test-reconciler-codegen.sh
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/knative.dev/pkg/tracing/propagation/http_format_sequence.go
  vendor/knative.dev/pkg/tracing/propagation/tracecontextb3/http_format.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#206 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#208 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#209 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved
