Repository knative-sandbox/control-protocol, pull requests merged in 2022-03, with the labels that each got.

#145 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: lgtm, approved, size/M

#147 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, size/XS, approved

#146 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#149 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, size/XS, approved

#150 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#152 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, size/XS, approved

#156 Updated top level README to indicate usage in distributed KafkaChannel
  README.md
Labels: size/S, lgtm, approved, kind/enhancement

#158 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, approved, size/XL

#151 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/exit.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/knative.dev/hack/CODE-OF-CONDUCT.md
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/reconciler-test/pkg/feature/steps.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#157 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, lgtm, approved
