Repository knative-sandbox/control-protocol, pull requests merged in 2022-04, with the labels that each got.

#160 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, approved, size/L

#161 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: lgtm, size/XS, approved

#163 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#164 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#165 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#166 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#168 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#153 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
Labels: lgtm, approved, size/M

#169 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/S, lgtm, approved

#170 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: lgtm, size/XS, approved

#172 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#173 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved
