Repository knative-sandbox/control-protocol, pull requests merged in 2023-03, with the labels that each got.

#267 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, skip-review

#265 Adding namespace to SAN
  .codecov.yaml
  pkg/certificates/certs.go
  pkg/certificates/constants.go
  pkg/certificates/reconciler/certificates.go
  pkg/certificates/reconciler/certificates_test.go
  pkg/network/tls.go
  pkg/reconciler/tls_dialer_factory.go
  pkg/reconciler/tls_dialer_factory_test.go
  pkg/test/tls.go
  test/conformance/feature/conformance_feature.go
Labels: lgtm, approved, size/L

#269 Add FakeDnsName
  pkg/certificates/certs.go
  pkg/certificates/constants.go
Labels: lgtm, size/XS, approved
