Repository knative-sandbox/control-protocol, pull requests merged in 2023-04, with the labels that each got.

#271 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#270 Support Ctrl, Data-Routing and Data-User certificates
  pkg/certificates/certs.go
  pkg/certificates/constants.go
  pkg/certificates/reconciler/certificates.go
  pkg/certificates/reconciler/certificates_test.go
  pkg/certificates/reconciler/controller.go
  pkg/network/tls.go
  pkg/reconciler/tls_dialer_factory.go
  pkg/reconciler/tls_dialer_factory_test.go
  pkg/test/tls.go
  test/conformance/feature/conformance_feature.go
Labels: lgtm, approved, size/L

#277 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#275 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#279 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, size/XS, approved, skip-review

#280 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
