Repository knative-sandbox/control-protocol, pull requests merged in 2023-01, with the labels that each got.

#241 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#242 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#246 Fix Conformance test due to parallel phases
  go.mod
  go.sum
  test/conformance/feature/conformance_feature.go
  test/conformance/resources/conformance_server/install.go
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/reconciler-test/pkg/environment/execution.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#247 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#248 Upgrade to new reconciler-test@release-1.9
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/environment/logging.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/modules.txt
Labels: lgtm, approved, size/M, kind/cleanup

#249 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/environment/logging.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/modules.txt
Labels: lgtm, approved, size/M
